### ISSUE TITLE
Implement gratuitous ARP sending

### ISSUE THREAD

**Issue by ants** [cybertec-postgresql/vip-manager#1]
Reduce failover time by proactively sending gratuitous ARP packets about the IP takeover.

**Comment by martinseener** [comment]
Does keepalived not just do the same? If so, we could see how they do it and reimplement it in Go here.

**Comment by ants** [comment]
Gratuitous ARP is actually quite simple, it's just an ARP request message to broadcast MAC with both sender and target address set to the address we want to announce. [Wikipedia has an overview](https://en.wikipedia.org/wiki/Address_Resolution_Protocol#ARP_announcements).

I don't think any standard OS tools are able to do GARP. I know resource-agents has [their own implementation](https://github.com/ClusterLabs/resource-agents/blob/master/tools/send_arp.linux.c), but it would be nice to avoid a dependency on that. There are a couple of Go based ARP implementations on github. [This one](https://github.com/mdlayher/arp) looks like it should work.
