### ISSUE TITLE
etcd error: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint

### ISSUE THREAD

**Issue by namnh3111996** [cybertec-postgresql/vip-manager#103]
I am getting error like this, is it because vip-manager doesn't support etcdv3 (3.5) yet?
<img width="1160" alt="Screen Shot 2022-09-23 at 15 59 26" src="https://user-images.githubusercontent.com/108382068/191926527-a70396f6-abdc-4e97-a705-ecba8e7a0b16.png">

**Comment by pashagolub** [comment]
Hello, what version of vip-manager is involved?

**Comment by namnh3111996** [comment]
> Hello, what version of vip-manager is involved?

I use vip-manager version 1.0.2

**Comment by pashagolub** [comment]
Aha, that explains a lot. etcdv3 protocol is added recently and not released yet. You can try that by building the binary against head of the master branch. The instructions are straightforward and are available in the readme.

Let us know if you will succeed. Thanks in advance

**Comment by namnh3111996** [comment]
> Aha, that explains a lot. etcdv3 protocol is added recently and not released yet. You can try that by building the binary against head of the master branch. The instructions are straightforward and are available in the readme.
> 
> Let us know if you will succeed. Thanks in advance

Thank. When will you release the new version ? I'm using keepalived instead.

**Comment by pashagolub** [comment]
We do have plans to release beta shortly and depending on its success to plan an official release
