### ISSUE TITLE
Manage more than one VIP

### ISSUE THREAD

**Issue by ehansmair** [cybertec-postgresql/vip-manager#114]
I am thinking about using VIP-Manager to manage several VIPs on one machine. Each VIP with a different trigger-key and trigger-value. 
I need this in a collapsed configuration: One VIP for a Postgres-cluster, the other for a redundant fail save Apache cluster.

**Comment by markwort** [comment]
The simplest solution is to just run multiple vip-managers.
If your mapping is
1:1:1 (key, value, VIP)
then you should not be changing the application, but using more instances of it.

I hope that answers your question.
Besides: I am not sure if your apache cluster has something similar to the patroni leader key, which you can use to trigger?
Perhaps you're better off looking at something like `confd` .

Best regards
Julian
