### ISSUE TITLE
Vip-manager recognizes wrong state 

### ISSUE THREAD

**Issue by ehansmair** [cybertec-postgresql/vip-manager#125]
vip-manager has a problem when the VIP is a substring of the local address. 

VIP 10.27.176.21
local 10.27.176.218

results in:
Dec 21 15:59:45 pgclust0 vip-manager[3450]: 2022/12/21 15:59:45 IP address 10.27.176.21/23 state is true, desired false
Dec 21 15:59:45 pgclust0 vip-manager[3450]: 2022/12/21 15:59:45 Removing address 10.27.176.21/23 on eth0
Dec 21 15:59:45 pgclust0 vip-manager[3450]: 2022/12/21 15:59:45 Got error RTNETLINK answers: Cannot assign requested address

The node does not have assigned VIP to eth0, but thinks state is true. He tries to remove the VIP - which produces a error.

Version of vip-manager is vip-manager-1.0.2-1.x86_64.

Greetings

**Comment by pashagolub** [comment]
Hey,

Is this still an issue? My first guess would be the absence of the admin privileges. Can you confirm that?

Thanks a lot and Happy New Year!

**Comment by ehansmair** [comment]
Hi,

the admin rights are ok. 

Maybe we are using an ancient version (vip-manager-1.0.2-1.x86_64) from 
our repository?


Sincerely

Ernst Hansmair
_______________________________________
_______________________________________



Von:    "Pavlo Golub" ***@***.***>
An:     "cybertec-postgresql/vip-manager" ***@***.***>
Kopie:  "ehansmair" ***@***.***>, "Author" 
***@***.***>
Datum:  03.01.2023 10:09
Betreff:        Re: [cybertec-postgresql/vip-manager] Vip-manager 
recognizes wrong state  (Issue #125)



Hey,
Is this still an issue? My first guess would be the absence of the admin 
privileges. Can you confirm that?
Thanks a lot and Happy New Year!
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by pashagolub** [comment]
There are two stable version at the moment:
- 1.0.2
- 2.0.0

The main difference of the second is this release is incompatible with previous v1 releases. It uses etcd v3 API instead of deprecated v2 API.

So it's up to you what version to use or to what version to migrate.

There are some googling results worth to check probably, e.g. https://wiki.archlinux.org/title/Network_Debugging

Since we never faced with such an error, I blame your environment.

**Comment by FactorT** [comment]
Yes, this is a bug.
Created pull request [129](https://github.com/cybertec-postgresql/vip-manager/pull/129)
