### ISSUE TITLE
install rule broken

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#14]
The `install` rule in the `Makefile` appears to be broken, the files `package/scripts/init-systemd.service` and `package/scripts/init-systemv.sh` mentioned there do no longer exist and the file `vip-manager.default` is in `package/config`, not `package/scripts`.

**Comment by blogh** [comment]
Hi,

I am experiencing the same problem, should I make a MR with these changes ? 

* package/scripts/init-systemd.service ==> package/scripts/vip-manager.service
* package/scripts/init-systemv.sh ==> package/scripts/vip-manager
* vipconfig/vip-manager.yml ==> package/config/vip-manager.default

Like so :

```
install:
	install -d $(DESTDIR)/usr/bin
	install vip-manager $(DESTDIR)/usr/bin/vip-manager
	install -d $(DESTDIR)/lib/systemd/system
	install package/scripts/vip-manager.service $(DESTDIR)/lib/systemd/system/vip-manager.service
	install -d $(DESTDIR)/etc/init.d/
	install package/scripts/vip-manager $(DESTDIR)/etc/init.d/vip-manager
	install -d $(DESTDIR)/etc/default
	install package/config/vip-manager.default $(DESTDIR)/etc/default/vip-manager.yml
```


Is there another way around this ? sorry I am completely new to go.

Thanks for the project !

**Comment by markwort** [comment]
Thanks for the effort!
hey @mbanck , can you please confirm that these changes match the expectation people have for packages in debian?
I fear I know too little about what goes where in the debian ecosystem.

**Comment by blogh** [comment]
After playing with this during this afternoon, I was wrong about this :

```
	install package/config/vip-manager.default $(DESTDIR)/etc/default/vip-manager.yml
```

The old one was ok. Sorry for the hasty fix proposal.
```
	install vipconfig/vip-manager.yml $(DESTDIR)/etc/default/vip-manager.yml
```

**Comment by mbanck** [comment]
I kinda did the same thing in the Debian packaging, so +1 from me.
