### ISSUE TITLE
vip-manager 2.1 doesn't set vip on my environment

### ISSUE THREAD

**Issue by henriavelabarbe** [cybertec-postgresql/vip-manager#143]
Hi,
We are using Patroni and vip-manager since a few years without issue.
For our new installations on Redhat8, I migrated etcd to use api v3 in Patroni.
I also tried vip-manager 2.0 and 2.1 with etcd api v3 but vip-manager is not managing the vip as expected.
I see no error message but it simply doesn't allocate the vip.
Going back to etcd api v2 on Patroni and vip-manager 1.0.2 fixed my issue.
Any idea how to make it works with api v3 and how to debug vip-manager ?

Regards,
Henri

**Comment by pashagolub** [comment]
Can you provide any output foe the v2?

**Comment by henriavelabarbe** [comment]
I'll have to reinstall my test environment using api v3.
The issue is that I have no output from vip-manager.
The systemd service starts without any issue but it's like vip-manager doesn't see the leader key in etcd.
I also tried to start it manually but same issue.
When I use vip-manager 1.0.2 and etcd api v2, I got :
"IP address x.x.x.x/24 state is true, desired true."

But with v2.1 and etcd api v3, those lines are not shown.

Here is the vip-manager.yml config used with v1.0.2, with ips and passwords removed :
```
ip: "x.x.x.x"
netmask: 24
interface: "ens224"
trigger-key: "/postgresql/echozebra/leader"
trigger-value: "servername"
dcs-type: etcd
dcs-endpoints:
    - http://x.x.x.x:2379
    - http://x.x.x.x:2379
    - http://x.x.x.x:2379
etcd-user: root
etcd-password: "********"
```

And for v2.1, only the dcs-endpoint is modified to omit http:

```
ip: "x.x.x.x"
netmask: 24
interface: "ens224"
trigger-key: "/postgresql/echozebra/leader"
trigger-value: "servername"
dcs-type: etcd
dcs-endpoints:
    - x.x.x.x:2379
    - x.x.x.x:2379
    - x.x.x.x:2379
etcd-user: root
etcd-password: "********"
```
