### ISSUE TITLE
vip-manager continues to update the "desired" as true even when the whole etcd cluster is down.

### ISSUE THREAD

**Issue by g1patnaik** [cybertec-postgresql/vip-manager#146]
Hi,

I was testing vip-manager behavior and stop etcd services, cleaned up the whole directory physically and even shutdown the etcd servers. But vip-manager was still updating the desiredState as true:

Mar 27 09:33:14 confdctest01cn vip-manager: 2023/03/27 09:33:14 IP address 192.168.56.201/24 state is true, desired true

I am using the vip-manager-2.1.0-1.x86_64 and with etcd v3.

**Comment by g1patnaik** [comment]
Hi,

Can you kindly check on this if there is indeed a bug in the current version that's causing this?

**Comment by pashagolub** [comment]
Hey.

Would you please provide us with exact steps to reproduce this issue?

Thanks in advance
