### ISSUE TITLE
Tags/Releases

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#15]
There seem to be several versions in the Debian packaging or mentioned in commit messages (like adc9404d5a), but there are no tags or releases, is that intentional? Is the actual current version on the master branch 0.4, or is that some Debian package version?

**Comment by vitabaks** [comment]
It may be worth using something like goreleaser ?

https://github.com/goreleaser/goreleaser

**Comment by markwort** [comment]
added tags and a new release a couple of days ago...
https://github.com/cybertec-postgresql/vip-manager/releases/tag/v0.6
