### ISSUE TITLE
 IP address xxx.xx.xx.xxx/24 state is false, desired false

### ISSUE THREAD

**Issue by bakink** [cybertec-postgresql/vip-manager#151]
Hi 
i installled potroni 3.0.2, etcd 3.5.8 and vip-manager 2.1.0
But when i start the vip manager it gets  "IP address  IP address xxx.xx.xx.xxx/24 state is false, desired false state is false, desired false."
and virtual IP cannot start on interface. I think vip-manager can cannot connect to etcd.
Could you tell me if vip-manager need some additional configuration?
Regards.

#/usr/bin/vip-manager --config=/etc/default/vip-manager.yml

2023/05/05 17:35:17 Using config from file: /etc/default/vip-manager.yml
2023/05/05 17:35:17 This is the config that will be used:
        config : /etc/default/vip-manager.yml
        dcs-endpoints : [http://xxx.xx.xx.xxx:2379 http://xxx.xx.xx.xxx2:2379 http://xxx.xx.xx.xxx:2379]
        dcs-type : etcd
        hosting-type : basic
        hostingtype : basic
        interface : ens192
        interval : 1000
        ip : xxx.xx.xx.xxx
        manager-type : basic
        netmask : 24
        retry-after : 250
        retry-num : 2
        trigger-key : /service/postgres/leader
        trigger-value : tst-sql-evam2
        verbose : false
        version : false
2023/05/05 17:35:17 IP address xxx.xx.xx.xxx/24 state is false, desired false
2023/05/05 17:35:27 IP address xxx.xx.xx.xxx/24 state is false, desired false
^C2023/05/05 17:35:28 Received exit signal
2023/05/05 17:35:28 Removing address xxx.xx.xx.xxx/24 on ens192
2023/05/05 17:35:28 Got error RTNETLINK answers: Cannot assign requested address
{"level":"warn","ts":"2023-05-05T17:35:29.051+0300","logger":"etcd-client","caller":"v3@v3.5.6/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002056c0/xxx.xx.xx.xxx:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

etcdctl --endpoints=[http://xxx.xx.xx.xxx:2379,http://xxx.xx.xx.xxx:2379,http://xxx.xx.xx.xxx:2379](http://xxx.xx.xx.xxx:2379%2Chttp//xxx.xx.xx.xxx:2379,http://xxx.xx.xx.xxx:2379) endpoint health
http://xxx.xx.xx.xxx:2379/ is healthy: successfully committed proposal: took = 2.72383ms
http://xxx.xx.xx.xxx:2379/ is healthy: successfully committed proposal: took = 2.92425ms
http://xxx.xx.xx.xxx:2379/ is healthy: successfully committed proposal: took = 2.678277ms

**Comment by bakink** [comment]
etcdctl --endpoints=http://xxx.xx.xx.xxx:2379,http://xxx.xx.xx.xxx:2379,http://xxx.xx.xx.xxx:2379 endpoint health
http://xxx.xx.xx.xxx:2379 is healthy: successfully committed proposal: took = 2.72383ms
http://xxx.xx.xx.xxx:2379 is healthy: successfully committed proposal: took = 2.92425ms
http://xxx.xx.xx.xxx:2379 is healthy: successfully committed proposal: took = 2.678277ms

**Comment by tpo** [comment]
This looks suspicious:

> interface : ens192
> [...]
> 2023/05/05 17:35:28 Removing address xxx.xx.xx.xxx/24 on ens192
> 2023/05/05 17:35:28 Got error RTNETLINK answers: Cannot assign requested address

Are you able to add and remove some random IP address (192.168.x.y) to the interface as the user as which vip-manager is running?

**Comment by bakink** [comment]
Hi,
I can add/remove IP address on this interface.
Regards.

#ip addr add 172.25.81.104/24 dev ens192
#ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:ae:6e:74 brd ff:ff:ff:ff:ff:ff
    inet 172.25.81.102/24 brd 172.25.81.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet 172.25.81.104/24 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::5b4c:4bd5:3256:f02e/64 scope link dadfailed tentative noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::5c86:fcae:f195:e305/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
# ip addr delete 172.25.81.104/24 dev ens192
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:ae:6e:74 brd ff:ff:ff:ff:ff:ff
    inet 172.25.81.102/24 brd 172.25.81.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::5b4c:4bd5:3256:f02e/64 scope link dadfailed tentative noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::5c86:fcae:f195:e305/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
#

**Comment by Gruic** [comment]
I think I know what happened with this issue.  If you add/move cards in your system or you do a big kernel upgrade and the interface  name changes, you will experience this exact issue.  Check that your network interface device name actually matches what in your /etc/vip-manager/vip-manager.yml config file.
