### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#16]
I've committed a first pass of a vip-manager Debian package to https://salsa.debian.org/postgresql/vip-manager

Let me know if you have any comments and/or are interested in co-maintaining the package.

For the Debian packaging, it would be helpful (but not required) to have regular releases, see #15.

**Comment by vitabaks** [comment]
It may be worth using something like goreleaser ?

https://github.com/goreleaser/goreleaser

**Comment by mbanck** [comment]
I meant a source-code release, i.e. a tag or a proper release on Github

**Comment by markwort** [comment]
@mbanck please confirm whether this issue can be closed.

I can currently not reach (the salsa page)[https://salsa.debian.org/postgresql/vip-manager] , but (the debian ftp server)[https://ftp-master.debian.org/new/vip-manager_0.6+ds-1.html]  suggests that you were successful in building the package.

Is there something we can do about the `Changes` Section?
It currently only lists:
> * New upstream release.
(and some dependency changes...)

Would this require a file that lists Changes for each release? Or can this be extracted from the changes mentioned in the release?
Maybe I'm on the wrong path here as well, maybe it's not customary to include the project's change notes and only those directly regarding packaging?

**Comment by tpo** [comment]
Hi @mbanck & @markwort 

> Is there something we can do about the `Changes` Section?
> It currently only lists:
> 
> > * New upstream release.
> 
> (and some dependency changes...)
> 
> Would this require a file that lists Changes for each release? Or can this be extracted from the changes mentioned in the release?
> Maybe I'm on the wrong path here as well, maybe it's not customary to include the project's change notes and only those directly regarding packaging?

The "Changes" from the vip-manager release notes could certainly be included in `/usr/share/doc/vip-manager/changelog.Debian.gz`. Another widely used tradition in Debian packaging is to put the "upstream changelog" in its own file, for example `/usr/share/doc/vip-manager/changelog.gz`. Both approaches are OK and I think depend on @mbanck 's preference.

A related question is how to put those "Changes" into the Debian package. Is there a way to retrieve the release notes? Aka something like https://github.com/cybertec-postgresql/vip-manager/releases/tag/v0.6/release-notes. I have looked around but haven't found any info about that. If we can't retrieve those automatically, then someone will have to copy/paste/maintain them by hand in the Debian package.

**Comment by tpo** [comment]
@vitabaks :

> It may be worth using something like goreleaser ?
> 
> https://github.com/goreleaser/goreleaser

The standard under Debian is for the package build to be selfcontained with respect to Debian packages. That is, you can not use tools to build Debian packages, that are not available as Debian packages themselves. So to use goreleaser would require someone to package and maintain goreleaser for Debian.

Also the build mechanics under Debian are standardized. You can not clobber a Debian package together in any random way. The packaging and packaging tooling has to follow a given structure, so that other people can reproduce the package following a standard workflow and automated tools can manipulate them.

I have not had a look at goreleaser but the above are the constraints if you want to build a Debian package that will be part of a Debian release. All of this is documented in the Debian Developer documentation.

**Comment by mbanck** [comment]
> Hi @mbanck & @markwort
> 
> > Is there something we can do about the `Changes` Section?
> > It currently only lists:
> > > * New upstream release.
> > 
> > 
> > (and some dependency changes...)
> > Would this require a file that lists Changes for each release? Or can this be extracted from the changes mentioned in the release?
> > Maybe I'm on the wrong path here as well, maybe it's not customary to include the project's change notes and only those directly regarding packaging?
> 
> The "Changes" from the vip-manager release notes could certainly be included in `/usr/share/doc/vip-manager/changelog.Debian.gz`. Another widely used tradition in Debian packaging is to put the "upstream changelog" in its own file, for example `/usr/share/doc/vip-manager/changelog.gz`. Both approaches are OK and I think depend on @mbanck 's preference.
> 
> A related question is how to put those "Changes" into the Debian package. Is there a way to retrieve the release notes? Aka something like https://github.com/cybertec-postgresql/vip-manager/releases/tag/v0.6/release-notes. I have looked around but haven't found any info about that. If we can't retrieve those automatically, then someone will have to copy/paste/maintain them by hand in the Debian package.

Unless there is a `CHANGES` or (traditionally) `NEWS` file in the source tree itself that can be shipped in `/usr/share/doc/<package>/`, those changes would have to be assembled manually, yes.

For some packages, I do tend to add some "important changes include: <list>" after the "New upstream release", but not by default. I can try to do that next time if I don't forget.

In any case, I think this issue can be closed.
