### ISSUE TITLE
support callback when VIP switched(switch hook)

### ISSUE THREAD

**Issue by zhiqiangwang08** [cybertec-postgresql/vip-manager#172]
when VIP switch to another host,  run user's  script(bash script or python script ...)  through callback(hook). 
- before_vip_change
- after_vip_change

something very similar to  patroni's callbacks (on_role_change). 
Not sure if any plan to support such a feature.

Thanks

**Comment by pashagolub** [comment]
Hello. 

Sounds like a good idea. Do you have a WIP patch maybe? Pull requests are more than welcome

Thanks
