### ISSUE TITLE
Cannot assign address

### ISSUE THREAD

**Issue by ffeller** [cybertec-postgresql/vip-manager#179]
Hello all,
We're having an issue when starting vip-manager on a CentOS 7 box where it can't assign the ip address to the interface eth0.
Here are the output of the command:

[root@bdgerr00 default]# /home2/postgres/ha-patroni/bin/vip-manager --config /home2/postgres/ha-patroni/conf/vip-manager.yml
2023/11/08 16:06:34 Using config from file: /home2/postgres/ha-patroni/conf/vip-manager.yml
2023/11/08 16:06:34 This is the config that will be used:
	config : /home2/postgres/ha-patroni/conf/vip-manager.yml
	dcs-endpoints : [https://127.0.0.1:22379 https://bdgerr00:22379 https://bdgerr01:22379 https://aplgerr00:22379]
	dcs-type : etcd
	etcd-ca-file : /home2/postgres/ha-patroni/certs/rootCA.crt
	etcd-cert-file : /home2/postgres/ha-patroni/certs/node.crt
	etcd-key-file : /home2/postgres/ha-patroni/certs/node.key
	etcd-password : *****
	etcd-user : root
	hosting-type : basic
	hostingtype : basic
	interface : eth0
	interval : 1000
	ip : 10.200.95.3
	manager-type : basic
	netmask : 24
	retry-after : 250
	retry-num : 2
	trigger-key : /service/digitro/leader
	trigger-value : bdgerr00
	verbose : true
	version : false
2023/11/08 16:06:34 IP address 10.200.95.3/24 state is true, desired false
2023/11/08 16:06:34 Removing address 10.200.95.3/24 on eth0
2023/11/08 16:06:34 Got error RTNETLINK answers: Cannot assign requested address
2023/11/08 16:06:34 Error while acquiring virtual ip for this machine
2023/11/08 16:06:44 IP address 10.200.95.3/24 state is true, desired true

Doing the command ip manually it works.

[root@bdgerr00 default]# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 46:23:9e:48:c5:5e brd ff:ff:ff:ff:ff:ff
    inet 10.200.95.36/24 brd 10.200.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4423:9eff:fe48:c55e/64 scope link 
       valid_lft forever preferred_lft forever
[root@bdgerr00 default]# ip addr add 10.200.95.3/24 dev eth0 
[root@bdgerr00 default]# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 46:23:9e:48:c5:5e brd ff:ff:ff:ff:ff:ff
    inet 10.200.95.36/24 brd 10.200.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.200.95.3/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4423:9eff:fe48:c55e/64 scope link 
       valid_lft forever preferred_lft forever
[root@bdgerr00 default]# ip addr del 10.200.95.3/24 dev eth0 
[root@bdgerr00 default]# 

Any ideas?

Thanks in advance,
Flaris.

**Comment by dengbin40** [comment]
I'm having the same problem.
```
[root@pgsql3 default]# journalctl  -f -u vip-manager.service 
-- Logs begin at Mon 2024-01-08 19:26:47 HKT. --
Jan 08 19:33:29 pgsql3 vip-manager[1468]: netmask : 24
Jan 08 19:33:29 pgsql3 vip-manager[1468]: retry-after : 250
Jan 08 19:33:29 pgsql3 vip-manager[1468]: retry-num : 3
Jan 08 19:33:29 pgsql3 vip-manager[1468]: trigger-key : /service/etcd_patroni_pg/leader
Jan 08 19:33:29 pgsql3 vip-manager[1468]: trigger-value : pgsql3
Jan 08 19:33:29 pgsql3 vip-manager[1468]: verbose : false
Jan 08 19:33:29 pgsql3 vip-manager[1468]: version : false
Jan 08 19:33:29 pgsql3 vip-manager[1468]: 2024/01/08 19:33:29 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:33:29 pgsql3 vip-manager[1468]: 2024/01/08 19:33:29 etcd checker started up, found key /service/etcd_patroni_pg/leader
Jan 08 19:33:39 pgsql3 vip-manager[1468]: 2024/01/08 19:33:39 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:33:49 pgsql3 vip-manager[1468]: 2024/01/08 19:33:49 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:33:59 pgsql3 vip-manager[1468]: 2024/01/08 19:33:59 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:34:09 pgsql3 vip-manager[1468]: 2024/01/08 19:34:09 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:34:19 pgsql3 vip-manager[1468]: 2024/01/08 19:34:19 IP address 10.20.20.200/24 state is false, desired false
```

Doing the command ip manually it works.

```
[root@pgsql3 home]# ip addr add 10.20.20.200/24 brd 10.20.20.255 dev ens33 label ens33:1
[root@pgsql3 home]# ping 10.20.20.200
PING 10.20.20.200 (10.20.20.200) 56(84) bytes of data.
64 bytes from 10.20.20.200: icmp_seq=1 ttl=64 time=0.018 ms
64 bytes from 10.20.20.200: icmp_seq=2 ttl=64 time=0.025 ms
64 bytes from 10.20.20.200: icmp_seq=3 ttl=64 time=0.026 ms
```
# operating environment

| ipaddr      | PGsql | etcd Version | patroni Version |
|-------------|-------|---------------|------------------|
| 10.20.20.151| 15.5  | 3.3.11        | 3.2.1            |
| 10.20.20.152| 15.5  | 3.3.11        | 3.2.1            |
| 10.20.20.153| 15.5  | 3.3.11        | 3.2.1            |

# pgsql3 config
```
[root@pgsql3 default]# cat vip-manager.yml 
ip: 10.20.20.200
netmask: 24
interface: ens33
trigger-key: "/service/etcd_patroni_pg/leader"
trigger-value: "pgsql3"
hosting-type: basic
dcs-type: etcd
dcs-endpoints:
  - http://127.0.0.1:2379
  - http://10.20.20.151:2379
[root@pgsql3 default]# hostname
pgsql3
[root@pgsql3 default]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:1c:06:e4 brd ff:ff:ff:ff:ff:ff
    inet 10.20.20.153/24 brd 10.20.20.255 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
[root@pgsql3 default]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@pgsql3 default]# uname -a
Linux pgsql3 5.4.259-1.el7.elrepo.x86_64 #1 SMP Wed Oct 25 16:46:09 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@pgsql3 home]# systemctl restart  vip-manager && journalctl  -f -u vip-manager
-- Logs begin at Mon 2024-01-08 19:22:35 HKT. --
Jan 08 19:43:37 pgsql3 vip-manager[1506]: manager-type : basic
Jan 08 19:43:37 pgsql3 vip-manager[1506]: netmask : 24
Jan 08 19:43:37 pgsql3 vip-manager[1506]: retry-after : 250
Jan 08 19:43:37 pgsql3 vip-manager[1506]: retry-num : 3
Jan 08 19:43:37 pgsql3 vip-manager[1506]: trigger-key : /service/etcd_patroni_pg/leader
Jan 08 19:43:37 pgsql3 vip-manager[1506]: trigger-value : pgsql3
Jan 08 19:43:37 pgsql3 vip-manager[1506]: verbose : false
Jan 08 19:43:37 pgsql3 vip-manager[1506]: version : false
Jan 08 19:43:37 pgsql3 vip-manager[1506]: 2024/01/08 19:43:37 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:43:37 pgsql3 vip-manager[1506]: 2024/01/08 19:43:37 etcd checker started up, found key /service/etcd_patroni_pg/leader
Jan 08 19:43:47 pgsql3 vip-manager[1506]: 2024/01/08 19:43:47 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:43:57 pgsql3 vip-manager[1506]: 2024/01/08 19:43:57 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:44:07 pgsql3 vip-manager[1506]: 2024/01/08 19:44:07 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:44:17 pgsql3 vip-manager[1506]: 2024/01/08 19:44:17 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:44:27 pgsql3 vip-manager[1506]: 2024/01/08 19:44:27 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:44:37 pgsql3 vip-manager[1506]: 2024/01/08 19:44:37 IP address 10.20.20.200/24 state is false, desired false
Jan 08 19:44:47 pgsql3 vip-manager[1506]: 2024/01/08 19:44:47 IP address 10.20.20.200/24 state is false, desired false
[root@pgsql3 home]# etcdctl get /service/etcd_patroni_pg/leader
pgsql3
```
Execute `etcdctl get /service/etcd_patroni_pg/leader` The value and `hostname` are the same, but still can't bind a VIP

**Comment by ffeller** [comment]
Hello all,
In fact it worked assigning the IP address 10.200.95.6 to eth0. In both cases there was no IP conflicting.
No ideas what went on.
Regards,
Flaris.
