### ISSUE TITLE
Support multiple instances

### ISSUE THREAD

**Issue by caseyallenshobe** [cybertec-postgresql/vip-manager#18]
The current debian package sets up a systemd service that uses /etc/default/vip-manager.yml.  This doesn't allow for the use case of having more than one VIP allocated to a node.

I utilize a separate VIP for each database, and host some databases on the same clusters.  So I would propose the addition of the following in addition to creation of a /etc/vip-manager directory, to support this:

/lib/systemd/system/vip-manager@.service:
```
[Unit]
Description=VIP-Manager instance %i
Before=patroni.service
ConditionPathExists=/etc/vip-manager/%i.yml

[Service]
Type=simple
ExecStart=/usr/bin/vip-manager -config=/etc/vip-manager/%i.yml
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by markwort** [comment]
For the Debian crowd, this certainly seems useful!
I'm not really sure if this fits well with the existing packaging, maybe @mbanck wants to chime in here :)

**Comment by markwort** [comment]
Actually, I just checked the Debian Salsa repo, it looks like they already introduced this:
https://salsa.debian.org/postgresql/vip-manager/blob/master/debian/vip-manager@.service

Then I think we'd need to coordinate to make sure that an addition of such a service file in our repo doesn't interfere with their builds...
Question is anyway: How important is it that we provide builds for Debian ourselves, now that it's in the repo?

**Comment by mbanck** [comment]
Yeah, the Debian packaging supports multiple (Patroni) clusters, it just keeps the vip config in `/etc/patroni` instead; I don't mind having a `/etc/vip-manager/` directory, though it does not seem to be absolutely needed. In case vip-manager one day supports other HA solutions besides Patroni, it'd make sense.

**Comment by caseyallenshobe** [comment]
In my case, I only run a single Patroni instance, a single PostgreSQL instance per node.  But that instance may host 3 databases, each of which is accessed via a separate VIP.

**Comment by mbanck** [comment]
How would that work? IPs are instance-wide, not database-wide.

**Comment by caseyallenshobe** [comment]
The IP’s follow the instance of course.  But perhaps I have four databases on that instance and end up needing to move one to a different cluster.  Then it serves me to have one floating IP per database, so I can move the one relevant IP to the new cluster and leave the other three alone.

**Comment by mbanck** [comment]
Ok, so I guess the issue title should be "Support multiple VIPs for a single instance"? I don't know about vip-manager upstream, but I don't think that's a use-case the Debian packaging should support.

You can set it up yourself, of course, but that will require adjusting the systemd unit.

**Comment by caseyallenshobe** [comment]
The systemd target unit I pasted above accomplishes either one.  I meant “multiple instances” as in multiple vip-manager instances, regardless if how many Patroni instances.

**Comment by markwort** [comment]
It's probably not a good idea to have vip-manager itself handle more than one VIP.
First, it does no good in the scenario Casey outlined, where you probably wouldn't want to touch the VIPs that are not associated with the database that is moved to a different cluster.
Second, it's probably not that nice to implement. We'd then need a way of tracking association of VIPs and databases...

This is much easier solved on the systemd level, I think.


The current Service File resembles the expectation that a redhat user might have:
The application installs one Service file with everything set to a default. The redhat user might then change this service to accomodate his own config locations and directories and if he needs more services, he'd usually just copy the service file and create another service.
> At least that is my experience.

The debian users are accustomed to the more generic @ notation.
> I think...

We could provide two Service files: one enabling @ notation, which would be packaged into .DEBs and the current one would be packaged into .RPMs.
