### ISSUE TITLE
getMask function has some problem

### ISSUE THREAD

**Issue by zhongyibill** [cybertec-postgresql/vip-manager#224]
func getMask(vip netip.Addr, mask int) net.IPMask {
	if mask > 0 || mask < 33 {
		return net.CIDRMask(mask, 32)
	}
	var ip net.IP = vip.AsSlice()
	return ip.DefaultMask()
}

1. The condition (mask > 0 || mask < 33)  always is ture.
2. Suppose I have a vip which is IPV6, the mask maybe greater than 32. The function ( net.CIDRMask(mask, 32)) will trigger an bug

**Comment by pashagolub** [comment]
fixed by #225
