### ISSUE TITLE
No arp client available, skip send gratuitous ARP

### ISSUE THREAD

**Issue by mnietz** [cybertec-postgresql/vip-manager#272]
I have installed vip-manager2 from the PostgreSQL Apt-Repos, Version: 2.8.0-1.pgdg120+1. On switchover/failover no gratious arp is send out and therefor the requests are routed to the old leader until the arp-entry expires:

vip-manager[8662]: current leader from DCS: 
vip-manager[8662]: current leader from DCS: pg2
vip-manager[8662]: IP address 192.168.10.150/24 state is false, desired true
vip-manager[8662]: Configuring address 192.168.10.150/24 on ens18
====> vip-manager[8662]: No arp client available, skip send gratuitous ARP

The latest 2.8 version from Github works as expected:

Configuring address 192.168.10.150/24 on ens18
Sent gratuitous ARP reply
Sent gratuitous ARP request

Maybe a problem with the debian-build?

**Comment by pashagolub** [comment]
@df7cb how can we debug this in a proper way?

**Comment by df7cb** [comment]
@mbanck is updating the Debian package, thanks!

**Comment by mbanck** [comment]
It works as expected on my local testing 3-node patroni cluster with Debian 12/pgdg packages, we'll have to see what the problem is

**Comment by mbanck** [comment]
@mnietz if you restart the vip-manager service, are there any other logs/errors regarding `arp` or `ARP` in the journal?

**Comment by mnietz** [comment]
@mbanck : Thanks for testing

Your comment made me test it more deeply.

Instead of starting the service via systemd i tried it from the command-line and it works as expected. Looking for differences in the flags from the config-file and the command-line i've recognized that the Problem is VIP_RETRY_NUM=3.

If it is enabled the described problem occurs, if it commented out everything works.

As the flag is (no longer?) available on the command-line i guess it is obsolete.

Are you able to reproduce the issue?

Here's my vip-manager configuration for references:

```
VIP_IP="192.168.10.150"
VIP_NETMASK="24"
VIP_INTERFACE="ens18"
VIP_TRIGGER_KEY="/patroni/[REDACTED]/leader"
VIP_TRIGGER_VALUE="pg3.stage"
VIP_DCS_TYPE="etcd"
VIP_DCS_ENDPOINTS="https://pg1.stage:2379,https://pg2.stage:2379,https://pg3.stage:2379"

VIP_ETCD_USER="root"
VIP_ETCD_PASSWORD="[REDACTED]"

VIP_INTERVAL=1000
VIP_RETRY_AFTER=250
#VIP_RETRY_NUM=3
VIP_ETCD_CA_FILE=/etc/ssl/ca.crt
```

**Comment by mbanck-ntap** [comment]
Indeed, I can reproduce this with `VIP_RETRY_NUM=3` being active. However, I don't think that is the current default in the Debian package, maybe you picked it up a long time ago and carried it forward via upgrades and/or added it yourself?

What I see in the logs is that as long as `VIP_RETRY_NUM` is not in the conf, the following is printed on startup:
```
Nov 18 09:13:01 pg3 vip-manager[7143]:         retry-after : 250
Nov 18 09:13:01 pg3 vip-manager[7143]:         retry-num : 3
```

But as soon as I add it to the conf, `retry-num` disappears:
```
Nov 18 09:17:37 pg3 vip-manager[10637]:         retry-after : 250
```
So the flag is still there, but apparently no longer supposed to be set on the command-line? The same happens with `VIP_RETRY_AFTER` but this conf flag does not lead to ARP failing.

**Comment by mbanck-ntap** [comment]
@pashagolub could it be due to the `deprecated` map, as `retry_num` (with underscore) is marked deprecated and the `mapDeprecated` function unsets something at the end:
```
func mapDeprecated() error {
        deprecated := map[string]string{
                // "deprecated" : "new",
  [...]
                "retry_num":     "retry-num",
                "retry_after":   "retry-after",
        }
[...]
                        // if this is a valid mapping due to deprecation, set the new key explicitly to the value of the deprecated key.
                        viper.Set(v, viper.Get(k))
                        // "unset" the deprecated setting so it will not show up in our config later
                        viper.Set(k, "")

                }
        }
```

**Comment by mnietz** [comment]
Yes, you are right, it is not activated by default. We deploy the configuration via ansible and had this setting also in other installations. My output ist exactly the same like yours. But i wonder were's the connection between this setting and the arp client.

**Comment by mbanck-ntap** [comment]
> But i wonder were's the connection between this setting and the arp client.

Right, this looks like an independent problem we haven't diagnosed yet. I guess there is a corner case where the arp client fails to start if `retry-num=0/nil` which is triggered by the config problem

**Comment by mbanck-ntap** [comment]
Ok, I tried to set `--retry-num` on the command line and that is rejected. So probably the deprecation logic needs some fixup, to either drop `retry-num` from it entirely, or there needs to be an additional check that `retry-num=3` (or at least larger than zero) after the config has been evaluated.

**Comment by mbanck-ntap** [comment]
Hrm, so setting `retry-num` via a `.yml` configuration file still works, which makes me wonder that it being rejected on the command-line might be an oversight.

And there, if one sets `retry-num : 0` one can reproduce the problem with the ARP client missing; it is due to this code in `ipmanager/basicConfigurer_linux.go` not executing `arp.Dial` once if `RetryNum` is 0:
```
func (c *BasicConfigurer) createArpClient() (err error) {
        for i := 0; i < c.RetryNum; i++ {
                if c.arpClient, err = arp.Dial(&c.Iface); err == nil {
```
