### ISSUE TITLE
dcs-type patroni is not documented in README

### ISSUE THREAD

**Issue by mbanck-ntap** [cybertec-postgresql/vip-manager#275]
I guess the main vip-manager documentation is the README, but the new `patroni` DCS-type is not (yet) documented there.

Also, I guess if the Patroni REST API has basic auth (username/password) set, vip-manager cannot use it right now?

**Comment by pashagolub** [comment]
Yes, there is lack of documentation.
Yes, no support for auth yet.

**Comment by mbanck-ntap** [comment]
> Also, I guess if the Patroni REST API has basic auth (username/password) set, vip-manager cannot use it right now?

For some reason I thought vip-manager wouldn't work if I set `authorization` in the Patroni REST-API, but by default, the read-only endpoints are still reachable, so vip-manager works fine for me.

I was working on some basic auth stuff and had it building, but I need to find some time to test it properly.
