### ISSUE TITLE
README mentions hosting_type, but correct is hostingtype

### ISSUE THREAD

**Issue by tpo** [cybertec-postgresql/vip-manager#39]

**Comment by pashagolub** [comment]
But `hosting_type` is used in the configuration

**Comment by markwort** [comment]
as of v1.0, vip-manager will acceppt hostingtype, hosting-type, manager-type in yaml config or --manager-type as a flag, as well as: VIP_HOSTINGTYPE, VIP_HOSTING_TYPE, VIP_MANAGER_TYPE as environment variables. 
Note that only the last elements of each of the mentioned groups are not deprecated going forward.

All the details are in the README.md now as well
