### ISSUE TITLE
Improve config handling

### ISSUE THREAD

**Issue by markwort** [cybertec-postgresql/vip-manager#41]
In the beginning, only flags where available to configure vip-manager.
ENV variables where used in the Service file to define the Variables that would be inserted following the flags in the executing call in the Service.

In the meantime, I have added config file handling, where the file was parsed by our own code and precedence had to be handled explicitly (i.e. override values from config file with CLI settings etc.)

There has been an effort to enable vip-manager to talk to etcd Clusters using certificate authentication #28 .
That implementation itself introduces logic to retrieve ENV variables.

To try and clean up this mess, I have decided to use Viper ( https://github.com/spf13/viper ) to handle config stuff for us.
At the same time, I tried to clean up the mess of different naming-schemes for various variables and added appropriate deprecation notices (so far only for flags, as there was so far no possibility to "Get" ENV vars from within vip-manager, it was always through the service file, so the deprecation notes would show up there as well).

Please see branch https://github.com/cybertec-postgresql/vip-manager/tree/viper-config for the changes in main.go .
I have not yet updates the documentation or reference .yml config file to reflect the changes.

**Comment by markwort** [comment]
@tpo I would be glad if you could give me some input on these changes!

**Comment by tpo** [comment]
Hi @markwort !

Sorry for the delay ...

> @tpo I would be glad if you could give me some input on these changes!

I've the patches directly, eg:
* 425493163eaf3edbbf5dd50d3c76f8f081aa55a8
* 47770f8c6bbc5941e366cb453ca2de917383ee72
* 1866e5c0801c77647bd6b44fbc1d1333c3bbb591
