### ISSUE TITLE
create Dockerfile for building binary and possibly packages using golang image instead of golang:alpine

### ISSUE THREAD

**Issue by markwort** [cybertec-postgresql/vip-manager#44]
To facilitate building for other platforms (that don't support new enough golang version, see #42 ) we should consider creating a Dockerfile that uses golang, not golang:alpine (due to musl libc vs. glibc incompatibilities) and builds the binary.
That Dockerfile could be used to create packages as well, then we could create a github action that will automatically build and publish packages of new builds.

**Comment by pashagolub** [comment]
I would go with [goreleaser](https://github.com/goreleaser/goreleaser/) for building packages with GitHub Actions
