### ISSUE TITLE
Provide guidance on listen_addresses / other Postgres setup

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#51]
AFAICT, the documentation/README only describes the vip-manager part of the equation. However, for Postgres to actually listen to the vip, isn't there some setup needed? I guess you either need to set `listen_addresses` to `*`, or set `net.ipv4.ip_nonlocal_bind` to `1` or something? Otherwise, Postgres might be started before the vip is set and won't be able to bind to it.

The problem with `*` is that if you have multiple instances running concurrently, they will all bind to all VIPs which might not be what you want if VIPs are managed per-instance. It might not be a problem in practice though as usually the port will be different anyway.

Am I missing something obvious here that makes it just-work on the Postgres side?

**Comment by kmoppel** [comment]
Hi, you're right - something like `*` or `0.0.0.0` (IPv4 only) is needed also for the Postgres `listen_addresses` to activate the automatic binding...and indeed that might not be suitable for more complex use cases. Will add a note to the README.
