### ISSUE TITLE
broken Debian version number vip-manager_1.0_beta3-1_amd64.deb

### ISSUE THREAD

**Issue by tpo** [cybertec-postgresql/vip-manager#56]
So to me this is a minor problem, but maybe you can fix it up somewhere in your process:

```
dpkg -i vip-manager_1.0_beta3-1_amd64.deb 
dpkg: error processing archive vip-manager_1.0_beta3-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'vip-manager':
 'Version' field value '1.0_beta3-1': invalid character in version number
Errors were encountered while processing:
 vip-manager_1.0_beta3-1_amd64.deb
```

A valid version number/package name would be f.ex.

    vip-manager_1.0~beta3-1_amd64.deb

https://readme.phys.ethz.ch/documentation/debian_version_numbers/ has a nice overview of package versioning possiblities and logic.

workaround:

    dpkg -i --force-bad-version vip-manager_1.0~beta3-1_amd64.deb

**Comment by markwort** [comment]
Thank you for noticing, I've added a note into the Makefile, where this is handled, for future reference...
