### ISSUE TITLE
upgrade from 0.6.4 to 1.0-beta3 breaks because "one-dash" option -config doesn't exist any more

### ISSUE THREAD

**Issue by tpo** [cybertec-postgresql/vip-manager#57]
From syslog:
```
Oct 12 15:07:43 testmachine vip-manager[15756]: unknown shorthand flag: 'c' in -config=/etc/patroni/11-test.vip.yml
```

This is actually coming from the systemd config file:
```
# cat /etc/systemd/system/multi-user.target.wants/vip-manager@11-test.service
[...]
ExecStart=/usr/bin/vip-manager -config=/etc/patroni/%i.vip.yml
```

Other than that the next vip-manager seems to work with the old `/etc/patroni/%i.vip.yml` config file just fine. :+1: !

**Comment by markwort** [comment]
Hey @tpo , thanks for checking out the 1.0-beta3 release!
Unfortunately it is not possible to support both - and -- config flags with the viper and pflag library.
This is a breaking change and I have documented how to "migrate" here:
https://github.com/cybertec-postgresql/vip-manager#Migration-for-Service-Files-using-YAML-config-files

I know, breaking changes aren't always appreciated, however I hope that in the long run this will result in code that is easier to extend and maintain. I've spent considerable time optimizing the flag/parameter names to make sure they are as clear as possible and I've spent equally long to make sure that "old" parameter names are still useable, be it in the enviroment variables or within the config file. - vs. -- was the only thing I couldn't carry over.
