### ISSUE TITLE
unknown shorthand flag: 'c' in -config with vip-manager v1.0 deb package

### ISSUE THREAD

**Issue by vitabaks** [cybertec-postgresql/vip-manager#63]
FYI
vip-manager_1.0-1_amd64.deb  -> /lib/systemd/system/**vip-manager.service**

/usr/bin/vip-manager **-config**=/etc/default/vip-manager.yml

Failed to start Manages Virtual IP for Patroni.
```
Nov 04 16:01:07 pgnode01 systemd[1]: Started Manages Virtual IP for Patroni.
Nov 04 16:01:07 pgnode01 vip-manager[10730]: unknown shorthand flag: 'c' in -config=/etc/default/vip-manager.yml
```

Because the old keys in the YAML config files will be remapped to new keys, all that needs to be done is to add a single dash:
```
ExecStart=/usr/bin/vip-manager --config=/etc/default/vip-manager.yml
```

**Comment by markwort** [comment]
Dear Vitaliy,
thanks for giving the new release a spin already!

This breaking change has already been documented in the README.md:
https://github.com/cybertec-postgresql/vip-manager#migrating-configuration-from-releases-before-v10

And there was already another ticket for exactly the same thing:
#57 

I hope as somebody who does a lot of automation using ansible, you can appreciate that the config handling has been ironed out now.
Even if it means a few breakages once, I think the experience in the future will be better for everyone.


I know, everyone is lazy, just like I myself only seldomly check issues that have already been closed in other repos...
So I will leave this ticket open for a few weeks, as a totempole to people running into this "issue" on their first try of the new release in the near future :)

**Comment by vitabaks** [comment]
Hi @markwort !

> This breaking change has already been documented in the README.md:
> https://github.com/cybertec-postgresql/vip-manager#migrating-configuration-from-releases-before-v10
> 
> And there was already another ticket for exactly the same thing:
> #57

I have already read it.

What I meant was that in the vip-manager.service specified "-config" with a single dash. I considered this to be a bug in the vip-manager_1.0-1_amd64.deb package.

**Comment by markwort** [comment]
I'm sorry I misunderstood your original issue, @vitabaks .
It's fixed it now and I've created a new release to avoid any issues with updates, [v1.0.1](https://github.com/cybertec-postgresql/vip-manager/releases/tag/v1.0.1) .
