### ISSUE TITLE
Clarify "interactions with components outside of vip-manager"

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#68]
Both the `retry-num` and `retry-after` configuration parameters mention "interactions with components outside of vip-manager". I initially assumed this had something to do with communication with the DCS, but looking at the code, it seems to be about the arp client?

I would assume other "interactions with [other] components outside of vip-manager" would probably require other timeouts/number of retries, so being very unspecific here might not be helpful to the user.

**Comment by markwort** [comment]
You're right, at the moment the retry logic is only used with the ARP client and sending of ARP packages.
The idea was to at some point reuse these retry parameters for other components as well:
- etcd
- consul
- hetzner "robot" API
- hetzner cloud API

The last of those is still pending to be tested and merged, the second to last will receive an update in the same flush.
For the two DCS implementations, the use of retry logic would certainly be nice.
Let's continue discussion about that over at #69 and update this issue when we arrive at a conclusion there.
