### ISSUE TITLE
etcd error: 100: Key not found

### ISSUE THREAD

**Issue by lotusnoir** [cybertec-postgresql/vip-manager#72]
Hello,
I'm trying to configure this tool with my patroni installation, but it looks like it's not compatible when etcd v3 api :/

when i launch it i just have this errors:

`etcd error: 100: Key not found (/service/postgresql_sys)`

On etcd cluster this is a result
```
[16:39]root@etcd-02:~# etcdctl get /service/postgresql/leader
/service/postgresql/leader
postgresql-sys-01
```
How can i make it work ? 
Thanks in advance

**Comment by tpo** [comment]
vip-manager doesn't support the etcd v3 api. See #71

**Comment by lotusnoir** [comment]
OK thank you for the answer, its too bad, i finally used a haproxy to handle the vip...

**Comment by markwort** [comment]
I'm closing this ticket since I have reopened the #71 ticket, it contains more information and should be used to track the etcd v3 support.

Best regards
Julian
