### ISSUE TITLE
Feature for certificate authentification

### ISSUE THREAD

**Issue by Tiago-DBA** [cybertec-postgresql/vip-manager#82]
HI,

for etcds connection does vip-manager support cert-authentification  ?
The aim is to avoid to store user's password in the configuration file, because of security issues.

Thank you

**Comment by markwort** [comment]
If you had taken the time to search for the word "cert" on the main page of the repo or using the search function, you could have answered this question yourself. 🙂

It is already supported, you'll just have to pass the relevant environment variables, flags, or parameters in the yaml config file:
https://github.com/cybertec-postgresql/vip-manager#Configuration
