### ISSUE TITLE
Use "watcher" approach for reading the leader key

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/vip-manager#9]
This should give better reaction in case of failover/switchover.

Code examples:
https://github.com/cybertec-postgresql/vip-manager/commit/6283e5d42fef935fbe394e629b8533ecadf479fc#diff-12ad28f43514ed0c54441e98fb253348
https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L406

**Comment by pashagolub** [comment]
Is this still the case? @markwort @kmoppel

**Comment by pashagolub** [comment]
Closed due to inactivity.
